remote_theme: just-the-docs #jekyll-theme-yat #pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
#theme: jekyll-theme-minimal
title: "Thursday: Massive Stars in Binaries"
description: Jan Eldridge, Ryosuke Hirai, Sohan Ghodla, Ebraheem Farag


